paths:
  genomes_dir: "data/genomes"
  results_dir: "results"

execution:
  conda_env: "MGE_finder"

# Где искать входные данные
input_sources:
  - "/home/lam34/thermaceae_genomes/ncbi_dataset/data/"
  - "/home/lam34/Thermus_genomes/assemblies_hybracter_ver2/FINAL_OUTPUT/complete/"

# Профили Pfam для поиска интеграз
pfam_profiles:
  - "/home/lam34/MGE_finder/pfam/PF00589.hmm"
  - "/home/lam34/MGE_finder/pfam/PF22022.hmm"