execution:
  conda_env: "/home/lam34/miniforge3/envs/MGE_finder"
# Где искать входные данные
input_sources:
  - "/home/lam34/thermaceae_genomes/ncbi_dataset/data/"
  - "/home/lam34/Thermus_genomes/assemblies_hybracter_ver2/FINAL_OUTPUT/complete/"

# Куда класть сконвертированные .fna
genomes_dir: "data/genomes"

# Куда писать результаты пайплайна
results_dir: "results"

# Профили Pfam для поиска интеграз
pfam_profiles:
  - "pfam/PF00589.27.hmm"
  - "pfam/PF22022.2.hmm"