paths:
  rep_mge_fasta: "/home/lam34/MGE_finder/classification_investigation/clusterMGE/results_mge/rep_mge_nt.fa"
  output_dir: "/home/lam34/MGE_finder/classification_investigation/vcontact/results_vcontact"

execution:
  conda_env:  "vContact3"     # conda‑окружение с vContact2 и зависимостями