# Где лежат GBK с аннотированными MGE
paths:
  mge_gbk_pattern: "/home/lam34/MGE_finder/results/*/mge_annotated.gbk"

execution:
  conda_env: "MGE_finder"          # MMseqs2, Biopython, Snakemake

mmseqs:
  results_dir:      "results_mge"          # все выходы сюда
  tmp_dir:          "results_mge/tmp"
  db_prefix:        "results_mge/mge_db"
  cluster_prefix:   "results_mge/mge_cluster"
  repdb_prefix:     "results_mge/mge_repdb"
  min_seq_id:       0.9                   # ≥ 90 % идентичности
  coverage:         0.95                  # ≥ 95 % покрытия