# Где лежат FASTA с MGE последовательностями (пути относительно каталога clusterMGE/)
paths:
  mge_fasta_pattern: "../../finder_pipeline/results_deinococcales/*/mge_region.fa"
  mge_gbk_pattern: "../../finder_pipeline/results_deinococcales/*/mge_annotated.gbk"
  use_fasta: true

execution:
  conda_env: "IE_finder"

mmseqs:
  results_dir:      "results_mge"
  tmp_dir:          "results_mge/tmp"
  db_prefix:        "results_mge/mge_db"
  cluster_prefix:   "results_mge/mge_cluster"
  repdb_prefix:     "results_mge/mge_repdb"
  min_seq_id:       0.9
  coverage:         0.95
