paths:
  input_dir: ../finder_pipeline/results_deinococcales
  output_dir: results_deinococcales
  logger_dir: ../finder_pipeline/scripts
  run_padloc_script: scripts/padloc_wrapper.py

execution:
  conda_env: padloc
