# classification_config.yaml — пути относительно каталога protein_clusterization/, если не абсолютные

conda_env: "IE_finder"

proteins:
  pattern: "../bakta_pipeline/results_bakta_deinococcales/*/annotation.faa"

mmseqs:
  results_dir: "results"
  tmp_dir: "results/mmseqs_tmp"
  db_prefix: "results/mmseqs_db"
  cluster_prefix: "results/mmseqs_cluster"
  repdb_prefix: "results/mmseqs_repdb"
  clusters_dir: "results/clusters_rep_seqs"
  min_seq_id: 0.8
  coverage: 0.5
